---
- hosts: ansible-host-01
  become: True
  tasks: 
    - name:
      firewalld:
        port: 80/tcp
        state: enabled
        permanent: yes
      notify: Reload firewall
  handlers:
    - name: Reload firewall
      systemd:
        name: firewalld
        state: reloaded

...          
